### ISSUE TITLE
ciao: --extra-vars "ciao_dev=true" is not working

### ISSUE THREAD

**Issue by markdryan** [clearlinux/clear-config-management#57]
I get the following error on Ubuntu 16.04

```
TASK [clearlinux.ciao-controller : Wait for ciao build] ************************
fatal: [cnw-ctl]: FAILED! => {"ansible_job_id": "931226442981.29872", "changed": false, "cmd": "go get -v github.com/01org/ciao/...", "delta": "0:00:00.004935", "end": "2016-09-26 10:02:13.453133", "failed": true, "finished": 1, "rc": 2, "start": "2016-09-26 10:02:13.448198", "stderr": "go: GOPATH entry cannot start with shell metacharacter '~': \"~/go\"", "stdout": "", "stdout_lines": [], "warnings": []}
```

Updating the file to provide the full path fixes the issue.  Ideally, we want the go path to be read from the user's environment.

**Comment by albertomurillo** [comment]
The role is called with "become: yes"
https://github.com/clearlinux/clear-config-management/blob/master/examples/ciao/ciao_controllers.yml#L3

And later on "become: no" is used at tasks that should be run as a normal user.
https://github.com/clearlinux/clear-config-management/blob/master/roles/ciao-controller/tasks/main.yml#L17

This hides environment variables for the user running ansible.

A change is required to run all tasks with the current user and use "become: yes" only on the tasks that requires root privileges rather than run all tasks as root and use "become: no" on the tasks that has to be run as normal user.

After that, ansible_env.GOPATH can be used instead of the current "gopath" variable.
